micronaut:
  application:
    name: updatewithembeddedid
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#datasources:
#  default:
#    url: jdbc:oracle:thin:@192.168.200.17:1521/POWEHR
#    pooled: true
#    username: pandore
#    password: pandore
#    driverClassName: oracle.jdbc.OracleDriver
---
jpa:
  default:
    packages-to-scan:
      - updatewithembeddedid.entity
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
